#!/usr/bin/env bash
# MODULE: tor config baseline — enforce offline master key, 60-day signing-key lifetime, loopback Metrics/Control ports, control-port cookie auth, disabled relay stats across every torrc. Medium risk; recommended-off.
#
# apply.sh — back up every instance torrc, arm a 5-minute auto-revert latch, then
# edit each torrc in place to the config baseline and reload the instance.
# Idempotent; supports --dry-run. Refuses to mutate without
# --confirm-offline-master-key.

set -euo pipefail

_here=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
# shellcheck source=lib.sh
. "$_here/lib.sh"

tcb_parse_flags "$@"

# ---------------------------------------------------------------------------
# --cancel-safety-latch: disarm a pending auto-revert and exit.
# ---------------------------------------------------------------------------
if [ "$TCB_CANCEL_LATCH" -eq 1 ]; then
  if oa_latch_cancel "$TCB_MODULE"; then
    exit 0
  else
    exit 0   # nothing armed — already disarmed, not an error.
  fi
fi

# ---------------------------------------------------------------------------
# Discover instances.
# ---------------------------------------------------------------------------
instances=$(tcb_instances)
if [ -z "$instances" ]; then
  die "tor-config-baseline: no torrc found under $ONIONARMOR_TCB_INSTANCES_DIR/*/torrc or at $ONIONARMOR_TCB_TORRC"
fi

# ---------------------------------------------------------------------------
# Dry run: print the per-instance plan, change nothing.
# ---------------------------------------------------------------------------
if [ "$TCB_DRY_RUN" -eq 1 ]; then
  info "dry-run: tor-config-baseline (no host changes)"
  while IFS=$'\t' read -r inst torrc; do
    [ -n "$inst" ] || continue
    printf '\n=== tor@%s (%s) ===\n' "$inst" "$torrc"
    plan=$(tcb_plan_changes "$torrc")
    if [ -z "$plan" ]; then
      printf '  (already compliant — no changes)\n'
    else
      printf '%s\n' "$plan" | sed 's/^/  /'
      printf '  reload   -> %s reload tor@%s\n' "$ONIONARMOR_TCB_SYSTEMCTL" "$inst"
    fi
  done <<EOF
$instances
EOF
  printf '\nPreserved (never modified): ContactInfo MyFamily FamilyId ExitRelay SocksPort\n'
  exit 0
fi

# ---------------------------------------------------------------------------
# Mutation gate: OfflineMasterKey has real operational consequences.
# ---------------------------------------------------------------------------
if [ "$TCB_CONFIRM_OMK" -eq 0 ]; then
  die "tor-config-baseline: refusing to edit torrc without --confirm-offline-master-key.
  This baseline sets 'OfflineMasterKey 1', which requires you to rotate the
  relay's signing key and keep the ed25519 master identity key OFFLINE. Run with
  --dry-run to preview, then re-run with --confirm-offline-master-key once you
  understand the operational impact (see the module README)."
fi

audit_log tcb.apply.start "instances=$(printf '%s' "$instances" | awk '{print $1}' | tr '\n' ',')"

# ---------------------------------------------------------------------------
# 1. Back up every torrc + render a restore script BEFORE editing anything.
# ---------------------------------------------------------------------------
backup_dir=$(tcb_backup_dir)
mkdir -p "$backup_dir" || die "cannot create backup dir $backup_dir"

restore_script=$(tcb_restore_script_path)
restore_tmp="$restore_script.tmp.$$"
{
  printf '#!/usr/bin/env bash\n'
  printf '# Auto-generated by onionarmor tor-config-baseline — restores each torrc\n'
  printf '# from backup and reloads the instance. Fired by the safety latch or by\n'
  printf '# revert. Best-effort.\n'
  printf 'set -u\n'
} > "$restore_tmp" || die "cannot write restore script $restore_tmp"

while IFS=$'\t' read -r inst torrc; do
  [ -n "$inst" ] || continue
  bkp="$backup_dir/$inst.torrc"
  cp -p "$torrc" "$bkp" \
    || audit_fail_die tcb.apply.fail "stage=backup inst=$inst" "failed to back up $torrc -> $bkp"
  # Record the original path next to the backup so revert can find the target.
  printf '%s\n' "$torrc" > "$backup_dir/$inst.path" \
    || audit_fail_die tcb.apply.fail "stage=backup-path inst=$inst" "failed to record path for $inst"
  {
    printf 'cp -p %s %s && %s reload tor@%s\n' \
      "$(printf '%q' "$bkp")" "$(printf '%q' "$torrc")" \
      "$(printf '%q' "$ONIONARMOR_TCB_SYSTEMCTL")" "$inst"
  } >> "$restore_tmp"
done <<EOF
$instances
EOF
mv "$restore_tmp" "$restore_script" || { rm -f "$restore_tmp"; die "cannot move restore script into place"; }
chmod +x "$restore_script" 2>/dev/null || true
audit_log tcb.apply.backup "dir=$backup_dir restore=$restore_script"

# ---------------------------------------------------------------------------
# 2. Arm the safety latch (unless --no-safety-latch). A bad torrc edit can lock
#    the operator out of the control port or fail the reload, so we must have an
#    auto-revert in place BEFORE we touch any torrc. If arming fails, abort
#    before editing (and clean up the staged restore script).
# ---------------------------------------------------------------------------
latched=0
if [ "$TCB_SAFETY_LATCH" -eq 1 ]; then
  if ! command -v "$ONIONARMOR_AT_CMD" >/dev/null 2>&1; then
    audit_log tcb.apply.fail "stage=latch-precheck"
    die "tor-config-baseline: '$ONIONARMOR_AT_CMD' not found — needed for the auto-revert safety latch. Install it (apt install at && systemctl enable --now atd) or re-run with --no-safety-latch (console access required)."
  fi
  if ! oa_latch_arm "$TCB_MODULE" "$restore_script" "$TCB_LATCH_MIN"; then
    audit_log tcb.apply.fail "stage=latch-arm"
    die "tor-config-baseline: could not arm the safety latch — aborting before editing any torrc (re-run with --no-safety-latch only if you have console access)."
  fi
  latched=1
  info "armed safety latch (at job $OA_LATCH_JOBID): auto-revert in $TCB_LATCH_MIN min"
else
  warn "--no-safety-latch: no auto-revert scheduled — a broken torrc edit will NOT be rolled back automatically. Ensure you have console access."
fi

# ---------------------------------------------------------------------------
# 3. Edit each torrc idempotently; reload the instances that changed.
# ---------------------------------------------------------------------------
changed_count=0
while IFS=$'\t' read -r inst torrc; do
  [ -n "$inst" ] || continue
  rendered_tmp="$torrc.oa.tmp.$$"
  tcb_rewrite "$torrc" "$rendered_tmp" \
    || { rm -f "$rendered_tmp"; audit_fail_die tcb.apply.fail "stage=rewrite inst=$inst" "failed to rewrite $torrc"; }

  if cmp -s "$rendered_tmp" "$torrc"; then
    rm -f "$rendered_tmp"
    info "tor@$inst: already compliant — no change ($torrc)"
    continue
  fi

  mv "$rendered_tmp" "$torrc" \
    || { rm -f "$rendered_tmp"; audit_fail_die tcb.apply.fail "stage=write inst=$inst" "failed to write $torrc"; }
  changed_count=$((changed_count + 1))
  audit_log tcb.apply.edit "inst=$inst torrc=$torrc"
  info "tor@$inst: applied baseline ($torrc)"

  if tcb_reload_instance "$inst"; then
    audit_log tcb.apply.reload "inst=$inst ok=1"
    info "tor@$inst: reloaded"
  else
    audit_log tcb.apply.reload "inst=$inst ok=0"
    warn "tor@$inst: '$ONIONARMOR_TCB_SYSTEMCTL reload tor@$inst' returned nonzero — the safety latch will auto-revert if you do not cancel it"
  fi
done <<EOF
$instances
EOF

audit_log tcb.apply.done "changed=$changed_count latched=$latched"

# ---------------------------------------------------------------------------
# 4. Summary.
# ---------------------------------------------------------------------------
cat <<EOF

[tor-config-baseline] applied.
  instances : $(tcb_instance_count) torrc file(s)
  changed   : $changed_count
  backups   : $backup_dir
EOF

if [ "$latched" -eq 1 ]; then
  cat <<EOF

  *** AUTO-REVERT SAFETY LATCH ACTIVE — torrc edits will be rolled back in $TCB_LATCH_MIN minutes. ***
  Confirm every tor instance is healthy (control port reachable, reload clean),
  THEN cancel the latch within $TCB_LATCH_MIN min:

      atrm $OA_LATCH_JOBID
      $(oa_latch_cancel_cmd "$TCB_MODULE")
  If you do NOT cancel it, each torrc will be restored from backup and reloaded.
EOF
fi

cat <<EOF

Check status any time:  onionarmor audit  --module tor-config-baseline
Undo the posture:       onionarmor revert --module tor-config-baseline
EOF
